project:
  type: book

book:
  title: "Regression Models for Epidemiology"
  author: "Ezra Morrison"
  date: "7/6/2023"
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  chapters:
    - index.qmd
    - intro-to-GLMs.qmd
    - Linear-models-overview.qmd
    - logistic-regression.qmd
    - count-regression.qmd
    - intro-to-survival-analysis.qmd
    - proportional-hazards-models.qmd
    - coxph-model-building.qmd
    - parametric-survival-models.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
       dark: darkly
       light: cosmo
  pdf:
    documentclass: scrreprt


editor: source

