project:
  output-dir: _slides
  render:
    - intro-to-GLMs.qmd
    - intro-MLEs.qmd
    - glms.qmd
    - Linear-models-overview.qmd
    - logistic-regression.qmd
    - count-regression.qmd
    - time-to-event-models.qmd
    - intro-to-survival-analysis.qmd
    - proportional-hazards-models.qmd
    - coxph-model-building.qmd
    - parametric-survival-models.qmd

format: revealjs

execute:
  warning: false
  message: false
  cache: true
  freeze: auto  # re-render only when source changes
