project:
  type: book

book:
  title: "Regression Models for Epidemiology"
  author: "Ezra Morrison"
  date: last-modified
  date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
  reader-mode: true
  site-url: https://d-morrison.github.io/rme
  repo-url: https://github.com/d-morrison/rme
  repo-actions: [edit, issue]
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  chapters:
    - index.qmd
    - intro-to-GLMs.qmd
    - part: glms.qmd
      chapters:
       - Linear-models-overview.qmd
       - logistic-regression.qmd
       - count-regression.qmd
    - part: time-to-event-models.qmd
      chapters:
       - intro-to-survival-analysis.qmd
       - proportional-hazards-models.qmd
       - coxph-model-building.qmd
       - parametric-survival-models.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
       light: cosmo
       dark: darkly
  # pdf:
  #   documentclass: scrreprt

execute:
  cache: true
  freeze: auto  # re-render only when source changes

editor: source

