project:
  type: book

book:
  title: "Regression Models for Epidemiology"
  author:
    - name: "Ezra Morrison"
      url: https://demorrison.ucdavis.edu/
      affiliation: Department of Public Health Sciences, School of Medicine, University of California, Davis
  page-footer:
    left:
      - text: "Copyright 2023, Douglas Ezra Morrison"
    right:
      - text: "License"
        href: http://creativecommons.org/licenses/by-nc-nd/4.0/
  date: last-modified
  date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
  google-analytics: "G-W625DGE908"
  reader-mode: true
  repo-url: https://github.com/d-morrison/rme
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro-to-GLMs.qmd
    - part: glms.qmd
      chapters:
       - Linear-models-overview.qmd
       - logistic-regression.qmd
       - count-regression.qmd
    - part: time-to-event-models.qmd
      chapters:
       - intro-to-survival-analysis.qmd
       - proportional-hazards-models.qmd
       - coxph-model-building.qmd
       - parametric-survival-models.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    shift-heading-level-by: 1
    theme:
       light: cosmo
       dark: darkly
    code-tools: true
    code-fold: show
    code-link: true
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    code-summary: "Show the code"

  # pdf:
  #   documentclass: scrreprt

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true

execute:
  warning: false
  message: false
  cache: true
  freeze: auto  # re-render only when source changes

editor: source

